"""
core/completions.py
Shell completion script generator for Cleo CLI.

Usage:
  cleo completions bash    # output bash completion script
  cleo completions zsh     # output zsh completion script
  cleo completions install # auto-install to shell rc file
"""

from __future__ import annotations

import os
import sys


# ── Static data ─────────────────────────────────────────────────────────────

SUBCOMMANDS = [
    "onboard", "init", "configure", "chat", "run", "status", "scores",
    "doctor", "export", "cron", "gateway", "channels", "agents", "workflow",
    "chain", "search", "memory", "evolve", "install", "uninstall", "update",
    "logs", "plugins", "completions",
]

GATEWAY_ACTIONS = ["start", "stop", "restart", "status", "install", "uninstall"]
CHANNEL_ACTIONS = ["list", "enable", "disable", "status", "test"]
CRON_ACTIONS = ["list", "add", "remove", "run"]
CHAIN_ACTIONS = ["status", "balance", "init", "register", "health"]
MEMORY_ACTIONS = ["status", "search", "rebuild", "cleanup", "reindex"]
PLUGIN_ACTIONS = ["list", "install", "remove", "enable", "disable", "info"]
COMPLETION_SHELLS = ["bash", "zsh", "install"]


def _get_agent_names() -> list[str]:
    """Dynamically read agent names from config."""
    try:
        import yaml
        if os.path.exists("config/agents.yaml"):
            with open("config/agents.yaml") as f:
                cfg = yaml.safe_load(f) or {}
            return [a["id"] for a in cfg.get("agents", [])]
    except Exception:
        pass
    return ["leo", "jerry", "alic"]


def _get_workflow_names() -> list[str]:
    """Dynamically read workflow names."""
    try:
        wf_dir = "config/workflows"
        if os.path.isdir(wf_dir):
            return [f.replace(".yaml", "").replace(".yml", "")
                    for f in os.listdir(wf_dir)
                    if f.endswith((".yaml", ".yml"))]
    except Exception:
        pass
    return []


# ── Bash Completion ─────────────────────────────────────────────────────────

def generate_bash() -> str:
    """Generate bash completion script."""
    agents = " ".join(_get_agent_names())
    workflows = " ".join(_get_workflow_names())
    subcmds = " ".join(SUBCOMMANDS)
    gw_acts = " ".join(GATEWAY_ACTIONS)
    ch_acts = " ".join(CHANNEL_ACTIONS)
    plugin_acts = " ".join(PLUGIN_ACTIONS)

    return f'''# Cleo CLI bash completion
# Generated by: cleo completions bash
# Add to ~/.bashrc: eval "$(cleo completions bash)"

_cleo_complete() {{
    local cur prev words cword
    _get_comp_words_by_ref -n : cur prev words cword

    local subcmds="{subcmds}"
    local agents="{agents}"
    local workflows="{workflows}"

    case "${{prev}}" in
        cleo)
            COMPREPLY=( $(compgen -W "${{subcmds}}" -- "${{cur}}") )
            return 0
            ;;
        gateway)
            COMPREPLY=( $(compgen -W "{gw_acts}" -- "${{cur}}") )
            return 0
            ;;
        channels)
            COMPREPLY=( $(compgen -W "{ch_acts}" -- "${{cur}}") )
            return 0
            ;;
        plugins)
            COMPREPLY=( $(compgen -W "{plugin_acts}" -- "${{cur}}") )
            return 0
            ;;
        --agent|-a)
            COMPREPLY=( $(compgen -W "${{agents}}" -- "${{cur}}") )
            return 0
            ;;
        --status|-s)
            COMPREPLY=( $(compgen -W "pending claimed review completed failed cancelled paused" -- "${{cur}}") )
            return 0
            ;;
        --level)
            COMPREPLY=( $(compgen -W "error warning info debug" -- "${{cur}}") )
            return 0
            ;;
        --provider)
            COMPREPLY=( $(compgen -W "flock openai minimax ollama" -- "${{cur}}") )
            return 0
            ;;
        --template)
            COMPREPLY=( $(compgen -W "researcher coder debugger doc_writer" -- "${{cur}}") )
            return 0
            ;;
        --format|-f)
            COMPREPLY=( $(compgen -W "md json" -- "${{cur}}") )
            return 0
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh install" -- "${{cur}}") )
            return 0
            ;;
    esac

    # Sub-subcommands
    if [[ ${{cword}} -ge 2 ]]; then
        case "${{words[1]}}" in
            workflow)
                if [[ ${{cword}} -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list run" -- "${{cur}}") )
                elif [[ ${{cword}} -eq 3 && "${{words[2]}}" == "run" ]]; then
                    COMPREPLY=( $(compgen -W "${{workflows}}" -- "${{cur}}") )
                fi
                return 0
                ;;
            agents)
                if [[ ${{cword}} -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "create add" -- "${{cur}}") )
                fi
                return 0
                ;;
            logs)
                COMPREPLY=( $(compgen -W "--follow -f --agent --level --since --lines" -- "${{cur}}") )
                return 0
                ;;
            status)
                COMPREPLY=( $(compgen -W "--agent -a --status -s --since --search -q --json" -- "${{cur}}") )
                return 0
                ;;
            doctor)
                COMPREPLY=( $(compgen -W "--repair --deep --export --json" -- "${{cur}}") )
                return 0
                ;;
        esac
    fi

    # Default: suggest flags
    if [[ "${{cur}}" == -* ]]; then
        COMPREPLY=( $(compgen -W "--help --json --version" -- "${{cur}}") )
        return 0
    fi

    COMPREPLY=( $(compgen -W "${{subcmds}}" -- "${{cur}}") )
}}

complete -F _cleo_complete cleo
'''


# ── Zsh Completion ──────────────────────────────────────────────────────────

def generate_zsh() -> str:
    """Generate zsh completion script."""
    agents = " ".join(_get_agent_names())
    workflows = " ".join(_get_workflow_names())
    subcmds = " ".join(SUBCOMMANDS)

    return f'''#compdef cleo
# Cleo CLI zsh completion
# Generated by: cleo completions zsh
# Add to ~/.zshrc: eval "$(cleo completions zsh)"

_cleo() {{
    local -a subcmds agents
    subcmds=({subcmds})
    agents=({agents})

    _arguments -C \\
        '(-V --version){{-V,--version}}[Show version]' \\
        '--json[Output JSON format]' \\
        '1:command:->cmd' \\
        '*::arg:->args'

    case $state in
        cmd)
            _describe 'command' subcmds
            ;;
        args)
            case $words[1] in
                gateway)
                    _values 'action' start stop restart status install uninstall
                    ;;
                channels)
                    _values 'action' list enable disable status test
                    ;;
                plugins)
                    _values 'action' list install remove enable disable info
                    ;;
                logs)
                    _arguments \\
                        '(-f --follow){{-f,--follow}}[Follow log output]' \\
                        '--agent[Filter by agent]:agent:({agents})' \\
                        '--level[Filter by level]:level:(error warning info debug)' \\
                        '--since[Time range]:range:' \\
                        '--lines[Number of lines]:lines:'
                    ;;
                status)
                    _arguments \\
                        '(-a --agent){{-a,--agent}}[Filter by agent]:agent:({agents})' \\
                        '(-s --status){{-s,--status}}[Filter by status]:status:(pending claimed review completed failed)' \\
                        '--since[Time range]:range:' \\
                        '(-q --search){{-q,--search}}[Search descriptions]:query:'
                    ;;
                doctor)
                    _arguments \\
                        '--repair[Auto-fix issues]' \\
                        '--deep[Deep diagnostics]' \\
                        '--export[Export diagnostic report]'
                    ;;
                completions)
                    _values 'shell' bash zsh install
                    ;;
            esac
            ;;
    esac
}}

_cleo
'''


# ── Install ─────────────────────────────────────────────────────────────────

def install_completions() -> tuple[bool, str]:
    """Auto-install completions to the user's shell rc file.

    Returns (success, message).
    """
    shell = os.environ.get("SHELL", "/bin/zsh")

    if "zsh" in shell:
        rc_path = os.path.expanduser("~/.zshrc")
        line = 'eval "$(cleo completions zsh)"'
    elif "bash" in shell:
        rc_path = os.path.expanduser("~/.bashrc")
        line = 'eval "$(cleo completions bash)"'
    else:
        return False, f"Unsupported shell: {shell}. Manually add completion script."

    # Check if already installed
    if os.path.exists(rc_path):
        with open(rc_path, "r") as f:
            content = f.read()
        if "cleo completions" in content:
            return True, f"Already installed in {rc_path}"

    # Append
    try:
        with open(rc_path, "a") as f:
            f.write(f"\n# Cleo CLI completions\n{line}\n")
        return True, f"Installed to {rc_path}. Restart shell or run: source {rc_path}"
    except OSError as e:
        return False, f"Failed to write {rc_path}: {e}"
